name: Daily Check-in

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时执行一次
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.19'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.local/lib/python3.9/site-packages
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # 只在缓存未命中时安装浏览器
          if [ ! -d ~/.cache/ms-playwright ]; then
            playwright install --with-deps firefox
          fi

      - name: Execute script
        env:
          USERNAME_1: ${{ secrets.USERNAME_1 }}
          PASSWORD_1: ${{ secrets.PASSWORD_1 }}
          USERNAME_2: ${{ secrets.USERNAME_2 }}
          PASSWORD_2: ${{ secrets.PASSWORD_2 }}
          # 可以继续添加更多用户...
        run: |
          python main.py

      - name: Send Telegram Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_USERID: ${{ secrets.TELEGRAM_USERID }}
        if: ${{ success() && env.TELEGRAM_TOKEN != '' && env.TELEGRAM_USERID != '' }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id=${{ env.TELEGRAM_USERID }} \
          -d parse_mode=HTML \
          -d text="✅ <b>LINUX DO</b> 多用户每日签到成功完成"

      - name: Send Failure Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_USERID: ${{ secrets.TELEGRAM_USERID }}
        if: ${{ failure() && env.TELEGRAM_TOKEN != '' && env.TELEGRAM_USERID != '' }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ env.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id=${{ env.TELEGRAM_USERID }} \
          -d parse_mode=HTML \
          -d text="❌ <b>LINUX DO</b> 多用户每日签到失败"

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 10
          keep_minimum_runs: 6
